### ISSUE TITLE
allfiles_time.txt

### ISSUE THREAD

**Issue by sedaist** [mdenolle/NoisePy#24]
First of all thank you for writing such a program code for noise tomography.
When I run the program script S0B_to_ASDF.py it keeps giving an error as below.
I will be grateful if you could help me.

(noisepy) C:\Users\Erman Temel\NoisePy\src>python S0B_to_ASDF.py
'export' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\Erman Temel\anaconda3\envs\noisepy\lib\site-packages\pandas\core\indexes\base.py", line 2889, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 97, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
**KeyError: 'names'**

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "S0B_to_ASDF.py", line 104, in <module>
    all_stimes = noise_module.make_timestamps(prepro_para)
  File "C:\Users\Erman Temel\NoisePy\src\noise_module.py", line 95, in make_timestamps
    allfiles = tmp['names']
  File "C:\Users\Erman Temel\anaconda3\envs\noisepy\lib\site-packages\pandas\core\frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\Erman Temel\anaconda3\envs\noisepy\lib\site-packages\pandas\core\indexes\base.py", line 2891, in get_loc
    raise KeyError(key) from err
KeyError: 'names'

My allfiles_time.txt file was created as follows.

GA.c0ATU..SHZ.2017.274.sac,1506816495.0,1506902399.0
GA.c0ATU..SHZ.2017.275.sac,1506902400.0,1506988799.0
GA.c0ATU..SHZ.2017.276.sac,1506988800.0,1507075199.0
GA.c0ATU..SHZ.2017.277.sac,1507075200.0,1507161599.0
.......

rootpath  = '/Users/Erman Temel/NoisePy/src'                    
RAWDATA   = os.path.join(rootpath,'RAWDATA')                
DATADIR   = os.path.join(rootpath,'Ganos_sac')                         
locations = os.path.join(rootpath,'station.txt')                     

input_fmt = 'sac'                                                     
samp_freq = 200                                                          
stationxml= False                                                       
rm_resp   = 'no'                                                      
respdir   = os.path.join(rootpath,'resp')                               
freqmin   = 1                                                       
freqmax   = 10                                                         
flag      = False                                                    

wiki_file = os.path.join(rootpath,'allfiles_time.txt')                     
allfiles_path = os.path.join(DATADIR,'*/*'+input_fmt)                 
messydata = True                                                       

start_date = ['2017_10_01_0_0_0']                                       
end_date   = ['2017_10_07_23_59_59']                                      
inc_hours  = 24

**Comment by nghia1991ad** [comment]
Simply add this first line to your file:
names,starttime,endtime

Pandas needs this line to identify column. Good luck.

**Comment by chengxinjiang** [comment]
> Simply add this first line to your file:
> names,starttime,endtime
> 
> Pandas needs this line to identify column. Good luck.

@nghia1991ad Thanks so much for the help here. I am now closing this issue.
