### ISSUE TITLE
Bug in noise_module-whiten(data, fft_para)

### ISSUE THREAD

**Issue by ZHONG-YICHEN** [mdenolle/NoisePy#46]
run S1_fft_cc_MPI.py in my pc (both Mac and Win), find an error in whiten(data, fft_para):

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function convolve at 0x000001B5E125E620>) found for signature:
 
 >>> convolve(array(float64, 1d, C), array(float64, 1d, C), mode=Literal[str](same))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'np_convolve': File: numba\np\arraymath.py: Line 4392.
    With argument(s): '(array(float64, 1d, C), array(float64, 1d, C), mode=unicode_type)':
   Rejected as the implementation raised a specific error:
     TypingError: got an unexpected keyword argument 'mode'
  raised from C:\Users\admin\.conda\envs\noisepy\lib\site-packages\numba\core\typing\templates.py:791

During: resolving callee type: Function(<function convolve at 0x000001B5E125E620>)
During: typing of call at ../src\noise_module.py (1358)

File "..\src\noise_module.py", line 1358:
def moving_ave(A, N): ## change the moving average calculation to take as input N the full window length to smooth
    <source elided>
    # with length equal to the original array, discarding the added leading and trailing samples
    B = np.convolve(temp, np.ones(N)/N, mode='same')[N: -N]

My numba version is 0.56. How can I deal with problem? thanks a lot!

**Comment by ZHONG-YICHEN** [comment]
> 

Oh... My numpy version is 1.22. Is it causing this problem?

**Comment by lucioquadros** [comment]
I recently cloned NoisePy again and I ran into the same issue. The problem is related to the change to the moving_ave function made with [this](https://github.com/mdenolle/NoisePy/commit/c805ffe5ae49c979f2d881d47ae8fdb94295cf41) commit. The np.convolve function on Numba is implemented for only the first two arguments according to the [documentation](https://numba.readthedocs.io/en/stable/reference/numpysupported.html), therefore the keyword 'mode' implemented recently raises an exception.

A 'fix' for me was to revert to a commit before this change.

**Comment by chengxinjiang** [comment]
Thanks @lucioquadros for the share. The original moving_ave function indeed
works, but the new version relying on numpy convolution function can be
much faster. To fix the issue for the new version of moving_ave function,
one can simply remove the line of ***@***.***(nopython = True)" at the beginning
of the function to avoid it running on Numba.

**Comment by lucioquadros** [comment]
Thanks for the reply @chengxinjiang. I tried before to remove the Numba decorator, @jit(nopython = True). However, if I do that the error below occurs:

`found 6 stations in total
working on station AGLP and trace hhz_00
Traceback (most recent call last):
  File "S1_fft_cc_MPI.py", line 283, in <module>
    source_white = noise_module.noise_processing(fc_para,dataS)
  File "/workspace11/lucio/NoisePy_new/src/noise_module.py", line 507, in noise_processing
    source_white = whiten(white,fft_para)       # whiten and return FFT
  File "/workspace11/lucio/NoisePy_new/src/noise_module.py", line 1574, in whiten
    FFTRawSign = whiten_2D(data, fft_para, n_taper)
  File "/workspace11/lucio/NoisePy_new/src/noise_module.py", line 1534, in whiten_2D
    spec_out[:, ix00: ix11] /= moving_ave(np.abs(spec_out[:, ix00: ix11]), smooth_N)
  File "/workspace11/lucio/NoisePy_new/src/noise_module.py", line 1348, in moving_ave
    temp[N: -N] = A
ValueError: could not broadcast input array from shape (60,9001) into shape (60)`

**Comment by niyiyu** [comment]
Also mentioned in #37.  Looks like `moving_ave` is only for 1D array. We might need to update the function so that it works with 2D matrix (moving average of each row of a 2D matrix)?
```python
def moving_ave(A, N): 
      # A.shape: (188, 7300)
      # temp.shape: (208, )
      temp = np.zeros(len(A) + 2 * N)
      # set the central portion of the array to A
      temp[N: -N] = A
                   ^-----ValueError: could not broadcast input array from shape...

      # leading samples: equal to first sample of actual array
      temp[0: N] = temp[N]
      # trailing samples: Equal to last sample of actual array
      temp[-N:] = temp[-N-1]
      # convolve with a boxcar and normalize, and use only central portion of the result
      # with length equal to the original array, discarding the added leading and trailing samples
      B = np.convolve(temp, np.ones(N)/N, mode='same')[N: -N]
```

**Comment by nrich20** [comment]
@niyiyu I replaced my moving_ave method with your moving_ave_2D method and it seems to have worked out the original issues within the noise_module. However, a new bug has arisen when I try to run S1_fft_cc_MPI.py. This one seems to be located within the S1 file itself. The error message states: 

Exception has occurred: ValueError
could not broadcast input array from shape (1692000,) into shape (3384000,)
  File "C:\Users\Nikus\OneDrive\Documents\Work\NoisePy\NoisePy\src\S1_fft_cc_MPI.py", line 301, in <module>
    fft_array[iii] = data.reshape(data.size)
ValueError: could not broadcast input array from shape (1692000,) into shape (3384000,)

Not sure if this is a new bug or a result of me changing moving_ave to handle 2D arrays. Currently trying to debug it.

**Comment by niyiyu** [comment]
@nrich20 thanks for testing this! This ValueError has been reported in #29 . I think it's not a bug from `moving_ave` and might be another issue to solve (maybe inconsistency of saving rFFT?)
